### ISSUE TITLE
there is no Generation of Pseudo-ground-truths reconstruction weights?

### ISSUE THREAD

**Issue by foocker** [NikolaZubic/2dimageto3dmodel#12]
We can use the pre-trained model (already provided? checkpoints_recon/pretrained_reconstruction_cub/checkpoint_latest.pth. there is no weights.

**Comment by NikolaZubic** [comment]
Dear @foocker all models are in the [RELEASE](https://github.com/NikolaZubic/2dimageto3dmodel/releases/tag/metadata).
