### ISSUE TITLE
ValueError: Training a model requires the pseudo-ground-truth to be setup beforehand.

### ISSUE THREAD

**Issue by lw0210** [NikolaZubic/2dimageto3dmodel#5]
I recently read your paper and was very interested in it . I want to reproduce the code of this paper. When I followed your instructions, I found it difficult for me to run the commands（python main.py --dataset cub --batch_size 16 --weights pretrained_weights_cub and python main.py --dataset p3d --batch_size 16 --weights pretrained_weights_p3d.）.And the program displayed a value error that training a model requires the pseudo-ground-truth to be setup beforehand. And I don’t know how to solve the problem, so I turn to you for help.I'm sorry to bother you, but I'really eager to solve the problem. I hope to get your reply.Thank you!

**Comment by NikolaZubic** [comment]
Dear @lw0210 , we updated the code to ensure that everyone can do full experimentation on it.
