### ISSUE TITLE
inference with single RGB pictures

### ISSUE THREAD

**Issue by 523997931** [NikolaZubic/2dimageto3dmodel#6]
Hi,
I am interested with your work, it is wonderful, and I want to use my own picture to test the model, could you provided the pretrained model and inference scripts.

**Comment by NikolaZubic** [comment]
Dear @523997931 , everything is provided with the new Release and explained in README.md.

Thanks,
Nikola.

**Comment by mahnoor-fatima-saad** [comment]
Hi 
Were you able to solve this problem?
