### ISSUE TITLE
can't find the pseudogt_512*512\.npz file

### ISSUE THREAD

**Issue by Yangfuha** [NikolaZubic/2dimageto3dmodel#7]
Dear NikolaZubic:
               I want to quote your paper, but I can't find the  pseudogt_512*512\.npz file and can't reproduce it.  Can you give me the pseudogt_512*512\.npz file and help me reproduce it?   Thanks

**Comment by NikolaZubic** [comment]
Dear Yangfuha, we added a new release and updated README.md.
Now everything is here for experimentation.
