### ISSUE TITLE
No module named 'models.reconstruction'

### ISSUE THREAD

**Issue by lw0210** [NikolaZubic/2dimageto3dmodel#8]
Dear  NikolaZubic  :   
            Thanks for you updated the code recently.  Did you put the reconstruction.py  in the models folder？When I  run “python run_reconstruction.py --name pretrained_reconstruction_cub --dataset cub --batch_size 10 --generate_pseudogt” it  display  
No module named 'models.reconstruction.

**Comment by NikolaZubic** [comment]
Dear @lw0210 , thank you for the report. I forgot to add the reconstruction .py file. Now, it is uploaded.

**Comment by lw0210** [comment]
THanks,your reply is so timely.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NikolaZubic/2dimageto3dmodel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 晚上8:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NikolaZubic/2dimageto3dmodel] No module named 'models.reconstruction' (Issue #8)





 
Dear @lw0210 , thank you for the report. I forgot to add the reconstruction .py file. Now, it is uploaded.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
