### ISSUE TITLE
Where is cmr_data?

### ISSUE THREAD

**Issue by achhabria7** [NikolaZubic/2dimageto3dmodel#9]
Keep running into this issue 
`from cmr_data.p3d import P3dDataset` and 
`from cmr_data.p3d import CUBDataset`

but you do not have these files in your repo. I tried using cub_200_2011_dataset.py but it does not take in the same number of arguments as the CUBDataset class used in run_reconstruction.py.

**Comment by virajguntamukkala** [comment]
I am running into the same issue

**Comment by NikolaZubic** [comment]
@achhabria7 and @virajg224 , CMR data has been added.

**Comment by virajguntamukkala** [comment]
Thanks. How do I run this? I am getting this error "FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints_recon/pretrained_reconstruction_p3d/checkpoint_latest.pth'".
I ran '!python main.py --dataset p3d --batch_size 16 --weights pretrained_weights_p3d --save_results' then '!python run_reconstruction.py --name pretrained_reconstruction_p3d --dataset p3d --optimize_z0 --batch_size 10 --generate_pseudogt'

**Comment by NikolaZubic** [comment]
@virajg224 you need to download the necessary data, explained here:
https://github.com/NikolaZubic/2dimageto3dmodel/releases/tag/metadata

**Comment by virajguntamukkala** [comment]
Thanks. I added those files. I am getting this error "FileNotFoundError: No such file: '/content/2dimageto3dmodel/code/datasets/p3d/PASCAL3D+_release1.1/Images/car_pascal/2008_000028.jpg'". There is no PASCAL3D+_release1.1 file in the datasets/p3d/ folder. Do I need to download the dataset?

**Comment by NikolaZubic** [comment]
> Thanks. I added those files. I am getting this error "FileNotFoundError: No such file: '/content/2dimageto3dmodel/code/datasets/p3d/PASCAL3D+_release1.1/Images/car_pascal/2008_000028.jpg'". There is no PASCAL3D+_release1.1 file in the datasets/p3d/ folder. Do I need to download the dataset?

Yes.
